version: 2
updates:
  # Ruby dependencies
  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "develop"
    labels:
      - "dependencies"
      - "ruby"
    commit-message:
      prefix: "chore(deps)"
    open-pull-requests-limit: 10
    reviewers:
      - "Cyprien-png"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "develop"
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "chore(ci)"
    open-pull-requests-limit: 10
    reviewers:
      - "Cyprien-png" 